# For local development
canonifyURLs = true
publishDir = 'docs'

baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Phils Blog'
theme = "hugo-flex"

[params]
  summaries = true

[[menu.nav]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.nav]]
  name = "All Posts"
  url = "/posts"
  weight = 2

[[menu.nav]]
  name = "About"
  url = "/about"
  weight = 3

[[menu.nav]]
  name = "Tags"
  url = "/tags"
  weight = 4

