---
# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    deps:
      - build

  build:
    cmds:
      - hugo

  serve:
    cmds:
      - hugo server --buildDrafts
...
